resources:
  jobs:
    training_pipeline:
      name: training_pipeline
      parameters:
        - name: model_name
          default: ""
        - name: catalog
          default: "${var.catalog}"
        - name: git_commit
          default: "${var.git_commit}"
        - name: git_branch
          default: "${var.git_branch}"
      tasks:
        - task_key: prepare_training_set
          notebook_task:
            notebook_path: ../notebooks/prepare_training_set.py
            base_parameters:
              model_name: "{{job.parameters.model_name}}"
              catalog: "{{job.parameters.catalog}}"
        - task_key: fit_and_compare_hyperparams
          depends_on:
            - task_key: prepare_training_set
          notebook_task:
            notebook_path: ../notebooks/fit_and_compare_hyperparams.py
            base_parameters:
              model_name: "{{job.parameters.model_name}}"
              catalog: "{{job.parameters.catalog}}"
        - task_key: select_best_and_test
          depends_on:
            - task_key: fit_and_compare_hyperparams
          notebook_task:
            notebook_path: ../notebooks/select_best_and_test.py
            base_parameters:
              model_name: "{{job.parameters.model_name}}"
              catalog: "{{job.parameters.catalog}}"
              git_commit: "{{job.parameters.git_commit}}"
              git_branch: "{{job.parameters.git_branch}}"
        - task_key: register_model
          depends_on:
            - task_key: select_best_and_test
          notebook_task:
            notebook_path: ../notebooks/register_model.py
            base_parameters:
              model_name: "{{job.parameters.model_name}}"
              catalog: "{{job.parameters.catalog}}"
              git_commit: "{{job.parameters.git_commit}}"
              git_branch: "{{job.parameters.git_branch}}"
